name: easy_scanner
description: A document scanner app like TapScanner

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  flutter_svg: ^2.0.9
  
  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # File Operations
  share_plus: ^7.2.2
  file_picker: ^10.1.9
  image: ^4.1.3
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  
  # Fix the conflict by explicitly specifying the version
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/